# syntax=docker/dockerfile:1.6

FROM node:24-alpine AS base
RUN corepack enable
WORKDIR /app

# ------------------------------------------------------
# Pruner
# ------------------------------------------------------
FROM base AS pruner

COPY . .

RUN pnpm dlx turbo prune ws-backend --docker

# ------------------------------------------------------
# Installer
# ------------------------------------------------------
FROM base AS installer

COPY --from=pruner /app/out/json/ ./

RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    pnpm install --frozen-lockfile

# ------------------------------------------------------
# Builder
# ------------------------------------------------------
FROM base AS builder
WORKDIR /app
ENV NODE_ENV=production
ENV TURBO_TELEMETRY_DISABLED=1

ARG TURBO_TEAM
ENV TURBO_TEAM=$TURBO_TEAM

COPY --from=installer /app/ ./
COPY --from=pruner /app/out/full/ ./

RUN --mount=type=secret,id=turbo_token \
    --mount=type=cache,target=/root/.cache/turbo \
    TURBO_TOKEN="$(cat /run/secrets/turbo_token)" \
    pnpm turbo run build --filter=ws-backend

# ------------------------------------------------------
# Runtime
# ------------------------------------------------------
FROM node:24-alpine AS runner
RUN corepack enable
WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/ ./

EXPOSE 8000

CMD ["node", "apps/ws-backend/dist/server.js"]