name: Websocket_deployment

on:
  push:
    branches:
      - main
    paths:
      - "apps/ws-backend/**"
      - "packages/auth-utils/**"
      - "packages/db/**"
      - "packages/typescript-config/**"
      - "packages/redis/**"
      - "packages/kafka/**"
      - ".github/workflows/cd_ws.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.ws-be
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ws-backend:${{ github.sha }}

          build-args: |
            TURBO_TEAM=${{ secrets.TURBO_TEAM }}

          secrets: |
            turbo_token=${{ secrets.TURBO_TOKEN }}

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            mkdir -p /home/${{ secrets.SERVER_USER }}/app

            cat > /home/${{ secrets.SERVER_USER }}/app/backend.env << 'EOF'
            ${{ secrets.BACKEND_ENV_FILE }}
            EOF

            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ws-backend:${{ github.sha }}

            sudo docker stop ws-backend || true
            sudo docker rm ws-backend || true

            sudo docker run -d \
             --name ws-backend \
             -p 8080:8080 \
             --env-file /home/${{ secrets.SERVER_USER }}/app/backend.env \
             --restart unless-stopped \
             ${{ secrets.DOCKERHUB_USERNAME }}/ws-backend:${{ github.sha }}

            rm /home/${{ secrets.SERVER_USER }}/app/backend.env
